### ISSUE TITLE
Base Forms

### ISSUE THREAD

**Issue by ghostaccount737** [cidermole/hjerson#1]
Can you elaborate on how the base forms were extracted ? In the [paper](https://www.researchgate.net/publication/270877918_Hjerson_An_Open_Source_Tool_for_Automatic_Error_Classification_of_Machine_Translation_Output ) too the examples are mentioned only for English.

I suppose this implementation supports other languages too ?

**Comment by cidermole** [comment]
Hi PVinay737,

The software implementation is independent of how you extract base forms, and hence also independent of language.
You can use a stemmer, or anything else fancy, like project to a smaller vocabulary using word vectors and take nearest-neighbor word types there.

HTH,
David

**Comment by ghostaccount737** [comment]
Thanks for the suggestion !
