### ISSUE TITLE
hou to use？

### ISSUE THREAD

**Issue by genbei** [cidermole/hjerson#2]
Hello, I have a question. What's the difference?--ref reference ，--baseref reference.base 
I thought that after giving a machine translation and a manually modified translation, I could calculate the error classification.
In addition, the specific use of scripts, such as
`python hjerson.py -R data/dev.pe -H data/dev.mt  -B TEXT -b TEXT -s -m`
Are these four documents necessary? -R -H -B -b,Because I only have two documents on hand
Looking forward to your reply

**Comment by cidermole** [comment]
Hi genbei,

Sorry about the late answer...

baseref and basehyp are base forms of words. In English, that would be the word form as stated in a dictionary: without inflection such as singular/plural, cases, tense, etc. Typically, you would obtain the base forms with a stemmer from ref and hyp.

If you do not have base forms, you can pass the same documents to the pair -H/-B and the pair -h/-b. You would then be able to compute some of the metrics, like wer, hper, rper, ... correctly. However, the word error type categorisation and all metrics based on inflection errors would be wrong.
